### PR TITLE
Update with Remult Relations `.toOne` and `.toMany`

### PR DESCRIPTION
**Pull request by jycouet**
- [x] remove TMP_JYC
- [x] new formats (timestamp with time zone, json, jsonb)
- [x] refactor singular / plural
- [x] options to give different schemas
- [x] Relations.toOne & raw
- [x] Relations.toMany
- [x] entities & enums index.ts

### CODE REVIEW

**Comment by Yedidyar** [comment]
Great job do you need anything else from me?

**Comment by jycouet** [comment]
I think that now it's all good 👍
Do we need to add chageset?

**Comment by Yedidyar** [comment]
> I think that now it's all good 👍
> Do we need to add chageset?

Yes add changeset

**Comment by jycouet** [comment]
Hooo, I didn't realized that this was not merged! I did a demo today that didn't go as expected because of it.
I'll check another thing right now and let you know if we can merge :)

**Comment by jycouet** [comment]
Okay, I just added `schemas-prefix` _(one of the user I know will use this)_.
Could we merge and publish this one?

**Pull request merged**
