### PR TITLE
fix: pluralize keys kababToConstantCase to handle from camelCase space PascalCase & use kababToConstantCase on enum defaultVal

### PR DESCRIPTION
**Pull request by Yedidyar**

### CODE REVIEW

**Review by jycouet — CHANGES_REQUESTED** [review]
When testing this PR on my database, I noticed 2 things: 
## 1/ Case
All `key` of my entities are changing like: `@Entity('accounts', {` => `@Entity('Accounts', {`
Is it on purpose? I'm not expecting this, but you maybe have a reason?

### 2/ Pluzalize
`@Entity('peoples', {` is becoming `@Entity('People', {`
When fixing the case,  it will become: "people" and that will break the `graphql` part.
Because in graphql, we need a different singular and plural.
Maybe if the key and the camelClass name match, we could fallback to the previous strategy? Log something to warn users?

In this case, I should _(maybe?)_ have named the table `person` and not `people`, like this the library would give me the Class `Person` and the key `people`. (it's proper english, but less practicle in the codebase, things will not be side by side, I have a lot of related tables... Should I name person or people, ...)

This leads maybe to another question, I do have all my tables in singular (except my wrong english "people" ^^) but in general, it's the case: "user", "site", "contract", ...
What if people have all their tables in plural? "users", "sites", "contract", ...

So, in my project, I have: 
dbName: "account" (we don't really care about this name, but we infer everything from it)
Class name "Account"
key: "accounts"

To me, 
database names should be in singular
key should be in camelCase plural
class name should be in PascalCase singular

Maybe we could have a setting to say in what the database is: "dbTableNameMode: 'singular' | 'plural' = 'singular'"

---

All that being said, I don't really care about the "people" thing. A warning would be good if collision anyway. Then people will fix things after running the PR, And/or, we log something and we put another value to avoir a crash issue! (because with GraphQL it would crash)

**Comment by Yedidyar** [comment]
I don't know how to approach the warning can you do it?

**Comment by jycouet** [comment]
> I don't know how to approach the warning can you do it?
> 
> I add the same situation with the key staff

What do you think? Nice logs no? :D
image

**Comment by Yedidyar** [comment]
> > I don't know how to approach the warning can you do it?
> > I add the same situation with the key staff
> 
> What do you think? Nice logs no? :D image

yeah very cool

**Pull request merged**
